# Name: Britain Pathing Targets Generated
# Description: Data-driven Britain route targets extracted from ConficturaRepositoryDocs for shop signs, spawners, and locations.
# Author: ChatGPT Codex
# Shard: Confictura

BRITAIN_TARGET_SOURCE = 'ConficturaRepositoryDocs/ConficturaRepository.xml'
BRITAIN_REGION_RECTANGLES = [(2929, 985, 3055, 1127), (2940, 886, 3095, 990)]
BRITAIN_CITY_RECTANGLE = (2929, 985, 3055, 1127)
BRITAIN_CASTLE_RECTANGLE = (2940, 886, 3095, 990)

BRITAIN_TARGET_SUMMARY = {
    "shop_sign_count": 25,
    "npc_spawner_count": 121,
    "location_count": 56,
    "location_index_count": 2,
    "castle_focus_count": 63,
    "total_unique_coordinates": 204
}

BRITAIN_SHOP_SIGN_TARGETS = [
    {
        "name": 'Britain Healers',
        "destination": (2951, 1006, 5),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Beasts of Burden',
        "destination": (2951, 1021, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'The Magic Garden',
        "destination": (2956, 999, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'the Wizards Guild',
        "destination": (2968, 946, 0),
        "area": 'castle',
        "class_name": 'PublicDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'The Cleaver',
        "destination": (2968, 1062, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Bows',
        "destination": (2974, 1038, 32),
        "area": 'city',
        "class_name": 'MerchantsBook',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Good Eats',
        "destination": (2980, 999, 5),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Metal',
        "destination": (2981, 1024, 8),
        "area": 'city',
        "class_name": 'MerchantsBook',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": "the Unicorn's Horn Tavern",
        "destination": (2981, 1089, 5),
        "area": 'city',
        "class_name": 'PublicDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": "The Unicorn's Horn",
        "destination": (2982, 1086, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Strength and Steel',
        "destination": (2986, 1011, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'The Hammer and Anvil',
        "destination": (2986, 1025, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'The Grand Clock Makers',
        "destination": (2996, 1101, 5),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'The Royal Doctor',
        "destination": (2999, 919, 0),
        "area": 'castle',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Profuse Provisions',
        "destination": (3009, 1111, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Bank of Britain',
        "destination": (3015, 1056, 5),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'the Bank of Britain',
        "destination": (3017, 1055, 5),
        "area": 'city',
        "class_name": 'PublicDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Leather',
        "destination": (3021, 1026, 14),
        "area": 'city',
        "class_name": 'MerchantsBook',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Premier Gems',
        "destination": (3021, 1111, 1),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'The Oaken Oar',
        "destination": (3031, 1007, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'The Best Hides of Britain',
        "destination": (3031, 1026, 5),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": "The Bard's Tale",
        "destination": (3031, 1036, 5),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": "The Lord's Clothiers",
        "destination": (3040, 1095, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Wood',
        "destination": (3041, 1046, 9),
        "area": 'city',
        "class_name": 'MerchantsBook',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Rolling Log Goods',
        "destination": (3041, 1058, 15),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
]

BRITAIN_NPC_SPAWNER_TARGETS = [
    {
        "name": 'adventurernorth',
        "destination": (2930, 989, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2931, 1055, 22),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2931, 1124, 22),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (2932, 987, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2933, 989, 22),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (2935, 1030, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (2936, 1033, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (2939, 1078, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (2941, 986, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (2941, 1080, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (2941, 1111, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (2943, 986, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'animaltrainer',
        "destination": (2943, 1022, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (2943, 1113, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'healer',
        "destination": (2944, 1004, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'healerguildmaster',
        "destination": (2944, 1011, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'veterinarian',
        "destination": (2944, 1032, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'sheep',
        "destination": (2945, 1039, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'gypsylady',
        "destination": (2948, 1085, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'horse',
        "destination": (2949, 1032, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'herbalist',
        "destination": (2952, 994, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2953, 1011, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (2958, 1043, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (2958, 1118, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (2959, 1037, 2),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'butcher',
        "destination": (2959, 1062, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2960, 898, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2961, 961, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'townguards',
        "destination": (2961, 1073, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (2962, 1039, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (2962, 1114, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'cow',
        "destination": (2963, 1066, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (2965, 980, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TavernPatronNorth',
        "destination": (2966, 923, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'alchemist',
        "destination": (2966, 952, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TavernPatronsouth',
        "destination": (2967, 921, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TavernPatronNorth',
        "destination": (2968, 923, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'scribe',
        "destination": (2968, 932, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (2968, 977, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'waiter',
        "destination": (2969, 928, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'BrewCauldron',
        "destination": (2970, 956, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'cook',
        "destination": (2971, 905, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'MasterCook',
        "destination": (2971, 910, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TavernPatronsouth',
        "destination": (2971, 933, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TavernPatronNorth',
        "destination": (2972, 935, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TavernPatronsouth',
        "destination": (2973, 933, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'mage',
        "destination": (2973, 950, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'baker',
        "destination": (2973, 994, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'warriorguildmaster',
        "destination": (2973, 1041, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'weaponsmith',
        "destination": (2974, 1012, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (2974, 1047, 6),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'architect',
        "destination": (2975, 907, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (2976, 1049, 6),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'sherrythemouse',
        "destination": (2977, 906, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2977, 952, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'blacksmith',
        "destination": (2977, 1026, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'bowyer',
        "destination": (2978, 1036, 25),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (2978, 1047, 6),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (2980, 1074, 2),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'cook',
        "destination": (2981, 992, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'blacksmithguildmaster',
        "destination": (2981, 1023, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (2981, 1038, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (2982, 1036, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (2982, 1076, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (2984, 1073, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'tinkerguildmaster',
        "destination": (2988, 1103, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'epiccharacter',
        "destination": (2990, 902, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'tinker',
        "destination": (2990, 1096, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'ChucklesJester',
        "destination": (2991, 918, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2991, 992, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'townguards',
        "destination": (2995, 936, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (2997, 995, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2999, 1112, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (2999, 1124, 44),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'healer',
        "destination": (3000, 909, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (3000, 991, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'Dog:Cat:Mouse',
        "destination": (3000, 1049, 50),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3000, 1072, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'priest',
        "destination": (3001, 928, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'citymanager',
        "destination": (3003, 908, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'keeperofchivalry',
        "destination": (3006, 928, 21),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3008, 946, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'provisioner',
        "destination": (3008, 1105, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'kungfu',
        "destination": (3009, 1009, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'artist',
        "destination": (3011, 906, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'sage',
        "destination": (3011, 914, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'epiccharacter',
        "destination": (3011, 951, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'varietydealer',
        "destination": (3014, 908, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (3015, 1073, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (3018, 1070, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3020, 899, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3020, 961, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'cobbler',
        "destination": (3022, 1031, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'townherald',
        "destination": (3022, 1062, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'mapmaker',
        "destination": (3023, 1010, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'cartographersguildmaster',
        "destination": (3024, 1013, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'shipwright',
        "destination": (3024, 1017, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'leatherworker',
        "destination": (3024, 1026, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'bard',
        "destination": (3024, 1038, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'epiccharacter',
        "destination": (3025, 962, 40),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurereast',
        "destination": (3025, 1099, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'jeweler',
        "destination": (3026, 1106, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'furtrader',
        "destination": (3027, 1031, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (3027, 1080, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (3027, 1083, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3028, 1003, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurerwest',
        "destination": (3029, 1099, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (3030, 891, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (3031, 895, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'weaver',
        "destination": (3034, 1103, 1),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'fisherman',
        "destination": (3035, 989, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3037, 1061, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'tailor',
        "destination": (3037, 1100, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3040, 1112, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'carpenter',
        "destination": (3042, 1049, 5),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurersouth',
        "destination": (3048, 1020, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'adventurernorth',
        "destination": (3048, 1022, 0),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3048, 1023, 22),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3053, 1054, 22),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (3053, 1124, 22),
        "area": 'city',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
    {
        "name": 'TownGuards',
        "destination": (4106, 3240, 0),
        "area": 'dungeons',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
    },
]

BRITAIN_LOCATION_TARGETS = [
    {
        "name": 'City of Britain',
        "destination": (2934, 1067, 0),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'healer coffer',
        "destination": (2941, 1002, 5),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'hay',
        "destination": (2943, 1040, 0),
        "area": 'city',
        "class_name": 'HayCrate',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'stablemaster coffer',
        "destination": (2944, 1024, 6),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'holy water',
        "destination": (2948, 1001, 5),
        "area": 'city',
        "class_name": 'HolyWater',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'gypsy tarot cards',
        "destination": (2950, 1086, 6),
        "area": 'city',
        "class_name": 'DecoDeckOfTarot',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'herbalist coffer',
        "destination": (2954, 997, 11),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'butcher coffer',
        "destination": (2961, 1059, 6),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'alchemist coffer',
        "destination": (2964, 954, 26),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Scrap Iron Barrel',
        "destination": (2970, 1022, 2),
        "area": 'city',
        "class_name": 'ScrapIronBarrel',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'mage coffer',
        "destination": (2971, 948, 6),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'iron',
        "destination": (2972, 1010, 0),
        "area": 'city',
        "class_name": 'BasementDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'weaponmaster coffer',
        "destination": (2972, 1015, 6),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'librarian coffer',
        "destination": (2973, 937, 26),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Census Records',
        "destination": (2973, 938, 26),
        "area": 'castle',
        "class_name": 'CensusRecords',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'tarot cards',
        "destination": (2973, 948, 3),
        "area": 'castle',
        "class_name": 'DecoDeckOfTarot',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'baker coffer',
        "destination": (2975, 993, 11),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'bowyer coffer',
        "destination": (2975, 1038, 31),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'iron',
        "destination": (2978, 1024, 0),
        "area": 'city',
        "class_name": 'BasementDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'architect coffer',
        "destination": (2980, 909, 26),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'blacksmith coffer',
        "destination": (2984, 1024, 6),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Task Manager',
        "destination": (2986, 942, 0),
        "area": 'castle',
        "class_name": 'TaskManager',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Task Manager 150 Minutes',
        "destination": (2986, 943, 0),
        "area": 'castle',
        "class_name": 'TaskManager150Min',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Task Manager 200 Minutes',
        "destination": (2986, 944, 0),
        "area": 'castle',
        "class_name": 'TaskManager200Min',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Defenders of Sosaria',
        "destination": (2986, 1039, 5),
        "area": 'city',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Daily Task Manager',
        "destination": (2987, 942, 0),
        "area": 'castle',
        "class_name": 'TaskManagerDaily',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Task Manager 250 Minutes',
        "destination": (2987, 943, 0),
        "area": 'castle',
        "class_name": 'TaskManager250Min',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": "Lord British's Castle",
        "destination": (2988, 942, 0),
        "area": 'castle',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'tinker coffer',
        "destination": (2989, 1107, 11),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'iron',
        "destination": (2992, 1105, 5),
        "area": 'city',
        "class_name": 'BasementDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'knight coffer',
        "destination": (3001, 936, 23),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'holy water',
        "destination": (3001, 939, 20),
        "area": 'castle',
        "class_name": 'HolyWater',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'oak shelf',
        "destination": (3006, 1108, 0),
        "area": 'city',
        "class_name": 'PublicDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'painter coffer',
        "destination": (3008, 906, 3),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'sage coffer',
        "destination": (3008, 916, 0),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'provisioner coffer',
        "destination": (3008, 1107, 6),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'the Amaterasu Dojo',
        "destination": (3010, 1015, 5),
        "area": 'city',
        "class_name": 'PublicDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'monk coffer',
        "destination": (3012, 1007, 8),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Shrine of Durama',
        "destination": (3015, 1012, 0),
        "area": 'city',
        "class_name": 'AltarDurama',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'collector coffer',
        "destination": (3017, 916, 20),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'jeweler coffer',
        "destination": (3020, 1107, 6),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Seeking Brave Sailors',
        "destination": (3021, 1015, 5),
        "area": 'city',
        "class_name": 'FishingQuestBoard',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'tanner coffer',
        "destination": (3023, 1025, 11),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'shipwright coffer',
        "destination": (3025, 1009, 11),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'cloth',
        "destination": (3026, 1027, 5),
        "area": 'city',
        "class_name": 'BasementDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'bard coffer',
        "destination": (3029, 1037, 11),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'Exotic Fish Tub',
        "destination": (3031, 1008, 0),
        "area": 'city',
        "class_name": 'FishBarrel',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'docking lantern',
        "destination": (3033, 988, 7),
        "area": 'castle',
        "class_name": 'DockingLantern',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'fisherman coffer',
        "destination": (3033, 995, 5),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'cloth',
        "destination": (3035, 1097, 0),
        "area": 'city',
        "class_name": 'BasementDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'tailor coffer',
        "destination": (3035, 1102, 8),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'docking lantern',
        "destination": (3043, 911, 6),
        "area": 'castle',
        "class_name": 'DockingLantern',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'wood',
        "destination": (3044, 1049, 5),
        "area": 'city',
        "class_name": 'BasementDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'carpenter coffer',
        "destination": (3045, 1052, 11),
        "area": 'city',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'docking lantern',
        "destination": (3049, 1007, 7),
        "area": 'city',
        "class_name": 'DockingLantern',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
    {
        "name": 'British Family Tomb',
        "destination": (3067, 958, 3),
        "area": 'castle',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
    },
]

BRITAIN_LOCATION_INDEX_TARGETS = [
    {
        "name": 'Britain Castle',
        "destination": (2985, 932, 0),
        "area": 'castle',
        "class_name": 'LocationIndex',
        "source_file": 'Data/Location/MapLocations.xml',
    },
    {
        "name": 'Britain',
        "destination": (2999, 1044, 0),
        "area": 'city',
        "class_name": 'LocationIndex',
        "source_file": 'Data/Location/MapLocations.xml',
    },
]

BRITAIN_CASTLE_FOCUS_TARGETS = [
    {
        "name": 'adventurereast',
        "destination": (2941, 986, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'adventurerwest',
        "destination": (2943, 986, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TownGuards',
        "destination": (2960, 898, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TownGuards',
        "destination": (2961, 961, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'alchemist coffer',
        "destination": (2964, 954, 26),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'adventurereast',
        "destination": (2965, 980, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TavernPatronNorth',
        "destination": (2966, 923, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'alchemist',
        "destination": (2966, 952, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TavernPatronsouth',
        "destination": (2967, 921, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TavernPatronNorth',
        "destination": (2968, 923, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'scribe',
        "destination": (2968, 932, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'the Wizards Guild',
        "destination": (2968, 946, 0),
        "area": 'castle',
        "class_name": 'PublicDoor',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['shop_sign'],
    },
    {
        "name": 'adventurersouth',
        "destination": (2968, 977, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'waiter',
        "destination": (2969, 928, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'BrewCauldron',
        "destination": (2970, 956, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'cook',
        "destination": (2971, 905, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'MasterCook',
        "destination": (2971, 910, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TavernPatronsouth',
        "destination": (2971, 933, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'mage coffer',
        "destination": (2971, 948, 6),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'TavernPatronNorth',
        "destination": (2972, 935, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TavernPatronsouth',
        "destination": (2973, 933, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'librarian coffer',
        "destination": (2973, 937, 26),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'Census Records',
        "destination": (2973, 938, 26),
        "area": 'castle',
        "class_name": 'CensusRecords',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'tarot cards',
        "destination": (2973, 948, 3),
        "area": 'castle',
        "class_name": 'DecoDeckOfTarot',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'mage',
        "destination": (2973, 950, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'architect',
        "destination": (2975, 907, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'sherrythemouse',
        "destination": (2977, 906, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TownGuards',
        "destination": (2977, 952, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'architect coffer',
        "destination": (2980, 909, 26),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'Britain Castle',
        "destination": (2985, 932, 0),
        "area": 'castle',
        "class_name": 'LocationIndex',
        "source_file": 'Data/Location/MapLocations.xml',
        "source_kinds": ['location_index'],
    },
    {
        "name": 'Task Manager',
        "destination": (2986, 942, 0),
        "area": 'castle',
        "class_name": 'TaskManager',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'Task Manager 150 Minutes',
        "destination": (2986, 943, 0),
        "area": 'castle',
        "class_name": 'TaskManager150Min',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'Task Manager 200 Minutes',
        "destination": (2986, 944, 0),
        "area": 'castle',
        "class_name": 'TaskManager200Min',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'Daily Task Manager',
        "destination": (2987, 942, 0),
        "area": 'castle',
        "class_name": 'TaskManagerDaily',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'Task Manager 250 Minutes',
        "destination": (2987, 943, 0),
        "area": 'castle',
        "class_name": 'TaskManager250Min',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": "Lord British's Castle",
        "destination": (2988, 942, 0),
        "area": 'castle',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'epiccharacter',
        "destination": (2990, 902, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'ChucklesJester',
        "destination": (2991, 918, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'townguards',
        "destination": (2995, 936, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'The Royal Doctor',
        "destination": (2999, 919, 0),
        "area": 'castle',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['shop_sign'],
    },
    {
        "name": 'healer',
        "destination": (3000, 909, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'priest',
        "destination": (3001, 928, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'knight coffer',
        "destination": (3001, 936, 23),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'holy water',
        "destination": (3001, 939, 20),
        "area": 'castle',
        "class_name": 'HolyWater',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'citymanager',
        "destination": (3003, 908, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'keeperofchivalry',
        "destination": (3006, 928, 21),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'painter coffer',
        "destination": (3008, 906, 3),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'sage coffer',
        "destination": (3008, 916, 0),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'TownGuards',
        "destination": (3008, 946, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'artist',
        "destination": (3011, 906, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'sage',
        "destination": (3011, 914, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'epiccharacter',
        "destination": (3011, 951, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'varietydealer',
        "destination": (3014, 908, 20),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'collector coffer',
        "destination": (3017, 916, 20),
        "area": 'castle',
        "class_name": 'Coffer',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'TownGuards',
        "destination": (3020, 899, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'TownGuards',
        "destination": (3020, 961, 0),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'epiccharacter',
        "destination": (3025, 962, 40),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'adventurersouth',
        "destination": (3030, 891, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'adventurernorth',
        "destination": (3031, 895, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'docking lantern',
        "destination": (3033, 988, 7),
        "area": 'castle',
        "class_name": 'DockingLantern',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'fisherman',
        "destination": (3035, 989, 1),
        "area": 'castle',
        "class_name": 'Spawner',
        "source_file": 'Data/Spawns/towns.map',
        "source_kinds": ['npc_spawner'],
    },
    {
        "name": 'docking lantern',
        "destination": (3043, 911, 6),
        "area": 'castle',
        "class_name": 'DockingLantern',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
    {
        "name": 'British Family Tomb',
        "destination": (3067, 958, 3),
        "area": 'castle',
        "class_name": 'Static',
        "source_file": 'Data/Decoration/Sosaria/decorate.cfg',
        "source_kinds": ['location'],
    },
]

